### ISSUE TITLE
Is the guide still usable?

### ISSUE THREAD

**Issue by RobNether** [yuya373/emacs-slack#191]
What the guide suggests seems to be misaligned with how slack actually is. Slack is asking for the team to approve of the created app before tokens are created.

**Comment by benjamreynolds** [comment]
@whtfox These may be settings that the owner of your team has set, some screenshots or specific errors at what point in the process you received them would be helpful. I (very recently) set this up on two different slack teams and the guide as is worked fine. Id be glad to help you trouble shoot.

**Comment by ssefick** [comment]
I am receiving the error: "Failed to request slack-authorize: not_authed"

Any help would be greatly appreciated.

**Comment by zanemayo** [comment]
I got the same error, but then the next thing I got was asking for the slack code. 
I copied the slack code from the url of the browser window that had opened with the localhost:8080 callback and that worked

**Comment by bhyde** [comment]
I did manage to get this working, but I found the guide a puzzlement.

For example - It kind of implies there is an easy way and a hard way.  But it looks to me like you need to do at least some of the hard way, since otherwise you won't have a client secret.  Am I right?

So I did create my own client.  The instructions for that say little if anything about what permission scopes the client should be configured with.  I assumed it needed lots.  Was I right?

I think it it would be good to mention that "token" means the oauth2 token provided by the slack service which is part and parcel of granting the rights needed to interact with a workspace/team.   That while each team you setup via slack-register-team can use the same client they each need a unique oauth token (aka token).  Since some users won't be oauth mavins.

It's a bit opaque about what is going to be the role of the call back URL.  I think, assuming I got this all right, that it should mention.   (a) you want to pick a port that does not have anybody listening on it (I had something listening on 8080 which reacted in an unproductive way when it it got the call back).  (b) That the token which appears there does/or doesn't need a few characters added as a prefix.

That said i never did get it a useful oauth token via the call back url.

So I for my tokens I took the "easy" method; i.e. dug them out of the browser developer tools' network tab.  I'm bemused that works.

I doubt I would have got it working if not for the number of samples one can find using code search in github.  For example:[managing credentials with auth-source-pass](https://github.com/search?q=auth-source-pass-get%20slack-register-team&type=Code)

In the best of all possible worlds this boot strapping could spin up a emacs based http server to field the call back to the callback url and grab the token.  Shame the folks a slack didn't let me spec a data url for the call back url.   But, yeah, bright ideas are cheap.

**Comment by kidd** [comment]
The "easy way" only needs the token. Try with:

```
  (slack-register-team
   :name "team-name"
   :client-id "aaaaaaaaaaa.00000000000"
   :client-secret "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
   :token "xoxs-your-real-token"
   )
```

**Comment by vyorkin** [comment]
yeah, it seems that you don't need to specify `:client_secret` at all
