### ISSUE TITLE
Private channels are invisible

### ISSUE THREAD

**Issue by rgrinberg** [yuya373/emacs-slack#218]
Create a private channel in slack, and it will not be visible when you select a channel in emacs-select. It would be nice if this channel would be both visible and marked as private in the list of channels.

**Comment by Sliim** [comment]
Yup it could be cool to have private channel available in channel list :). I'm facing the same issue.

**Comment by benjamreynolds** [comment]
I am able to see private channels in my setup. I wonder what Im doing differently

**Comment by smk291** [comment]
Same problem here. @benjamreynolds could you share your setup? And you're sure these are private channels, i.e. only specific, invited users have access?

**Comment by smk291** [comment]
[This may be the problem](https://github.com/yuya373/emacs-slack/blob/master/slack-channel.el#L34). `channels.list` doesn't include private channels. When I have a moment, I'll fork, branch and try changing it myself.

**Comment by benjamreynolds** [comment]
Yup, you can see my config [here](https://github.com/benjamreynolds/dotfiles/blob/master/spacemacs.d/init.el#L252) in my dotfiles

**Comment by gdanov** [comment]
I confirm I see private channels. Could it be some org setting? One of the slacks I am registered with has very fine grained access config in the api.slack.com page

**Comment by howdoicomputer** [comment]
Mine are hidden as well. Weird.

**Comment by prosoitos** [comment]
Strangely, I can see some (but not all) of my private channels with `slack-channel-join`. The private groups I cannot see there, I can see with `slack-group-select` (while the ones I could see, I can't see with this later command).

The difference between the 2 sets of private channels is a total mystery to me. Clearly due to some mysterious Slack behaviour and nothing to do with this package.

`slack-select-rooms` is nice in that it can show them all.
