### ISSUE TITLE
Anyone else have major application hangs with this package?

### ISSUE THREAD

**Issue by tinder-jonathanwilner** [yuya373/emacs-slack#341]
Hi all - 

I'm a longtime user of emacs-slack on Mac OS X, with both the emacs-plus and emacs-mac packages. 
Does anyone else get seemingly random application hangs in other parts of Emacs when emacs-slack is loaded? It happens to me very frequently -  looking like it's got something to do possibly with flyspell-post-command-hook, but I am not expert enough to really track it down, outside of looking at the debug mode & running the profiler. I usually have to send a USR2 signal to get back control of Emacs. 

I've tried just about everything to figure out if it's something in my config, but at this point, I've stopped using the package.

TIA.

**Comment by ErwinJunge** [comment]
I also ran into hangs just now when trying this package for the first time. For me the problem was that `notify-send` hanged because notification-daemon didn't have the correct value for `DISPLAY`. Running i3 directly without display manager. See https://github.com/dunst-project/dunst/issues/347 for details. Specifically the tip in https://github.com/dunst-project/dunst/issues/347#issuecomment-319370556 helped.
