### ISSUE TITLE
Is there a way to use this package without installing my app into the workspace?

### ISSUE THREAD

**Issue by parhamdoustdar** [yuya373/emacs-slack#383]
Hi,

I'm trying to use emacs-slack with a high-traffic workspace, Kubernetes. When I did the configuration steps and got to the step where I had to authorize the app, I got a prompt saying that I need to request a workspace admin to install my app here.

Is there a way not to have to do this in every single workspace I will be joining in the future?

Thanks!

**Comment by yuya373** [comment]
[This](https://github.com/yuya373/emacs-slack#1-from-request-payload) is the way to get token without installing this package as app.

I tried Kubernetes workspace with this package but Emacs hangs frequently.
This package gets all users in advance, so hangs on workspace where there are many users. 
In order to be able to use this package with a large workspace, we have to find a way to obtain user information as needed.
