### ISSUE TITLE
Some MPDMs can't be opened in emacs-slack, and give no notifications

### ISSUE THREAD

**Issue by matthew-piziak** [yuya373/emacs-slack#476]
I noticed that I missed some multi-person direct message notifications in my `emacs-slack`. I opened the web Slack client and looked at the names in the message.

Now, interestingly,  when I ran `slack-select-rooms`, I could _see_ the group. Twice!
```
Tempus - mpdm-nullam.libero--mauris.consequat--quis.varius--dictum.aliquam--arcu.rutrum-1
Tempus - mpdm-nullam.libero--mauris.consequat--quis.varius--dictum.aliquam--arcu.rutrum-1
```

Selecting the group logs `No Message in mpdm-nullam.libero--mauris.consequat--quis.varius--dictum.aliquam--arcu.rutrum-1, fetching from server...`, but no buffer is opened nor appears at all.

I can also see this group through `slack-group-select`. Same behavior, but this time it only shows up once.

However, I _can_ perform `slack-group-mpim-open`, select the users, and then the correct buffer opens up. And when I do that, tracking for that buffer starts working, so that I get notifications for new messages in that group.

I'd expect for these MPDMs to behave like rooms or DMs for the purposes of notification and navigation, without having to manually open them up.

**Environment:**
 - OS: NixOS
 - Emacs Version: GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.5) of 2019-07-22
 - emacs-slack Version: df605f4

**Comment by umairbinaltaf** [comment]
I see a similar behavior.  MPDMs that have been created (by me or anyone in our workspace) since I started emacs and`emacs-slack` do not open in a buffer.  I can see the MPDM in the list returned by  `slack-group-select` but I cannot open it in a buffer. Restarting `emacs-slack` with `slack-ws-close` and `slack-start` has no effect. I can only open those MDPM buffers only when I restart emacs and `emacs-slack`, 

Environment:

- OS: MacOS
- GNU Emacs 26.2 (build 1, x86_64-apple-darwin17.7.0, Carbon Version 158 AppKit 1561.6) of 2019-04-14
-  emacs-slack Version: MELPA 20190710.749

**Comment by yuya373** [comment]
Does [this](https://github.com/yuya373/emacs-slack/commit/a720d4d040c71e14b9a7e2a4848bc7555d60d375) commit fix the issue?

**Comment by umairbinaltaf** [comment]
As far as I can check, it does. With the new commit, I can create an MPDM and open a buffer for it with `slack-group-select`. No need to restart Emacs anymore. I will update here with the notification issue as I use it more during the work week.

**Comment by umairbinaltaf** [comment]
I get notifications from  newly created MPDMs by others  as well.

**Comment by nicklan** [comment]
I have a similar issue.  In my case it's a private channel. I'm running melpa "20190803.1406", but there are private channels that I was invited to where I get the "No Message in [group name], fetching from server...", with no further activity.

lemme know if there's anything I can do to help.

**Comment by matthew-piziak** [comment]
New MPDMs are fixed for me now! Sometimes I don't get notifications on threads though.

**Comment by chasecaleb** [comment]
Unfortunately it looks like this issue is back. I first noticed it within the last few days, but I also haven't had any new multi-person DMs so I wouldn't be surprised if this has been going on for longer... unfortunately I have no idea when this was last working for me since I rarely use MPDMs. I'm on the current commit of master: https://github.com/yuya373/emacs-slack/commit/ae1d742 

I haven't had a chance to dig into this deeper to see what is causing it, but I'm happy to do whatever troubleshooting is requested if necessary. Creating a test slack workspace with several accounts sounds like a pain so I've been avoiding trying to figure it out myself, for lack of better ideas how.
