### ISSUE TITLE
Images not rendering despite (setq slack-render-image-p t) being set

### ISSUE THREAD

**Issue by triclops200** [yuya373/emacs-slack#495]
**Describe the bug**
Images in the slack channel appeare like ![this](https://user-images.githubusercontent.com/343522/72291178-d2181800-361c-11ea-97be-2fae70ca926f.png) in my emacs

**To Reproduce**
1. Go to a channel with images

**Backtrace**
```
ImageMagick error: improper image header `/tmp/<ommitted>.png' @ error/png.c/ReadPNGImage/4092 [4 times]

```

**Expected behavior**
Images displayed

**Environment:**
 - OS: ubuntu 19.10
 - Emacs Version: 27.0.50
 - emacs-slack Version: latest commit

**Comment by yuya373** [comment]
I don't think this package is the cause. I think the file is corrupted.

**Comment by triclops200** [comment]
I would agree with you, except *every* image is like that on slack.

**Comment by yuya373** [comment]
Can you open other png file with `find-file` and displayed correctly?

**Comment by triclops200** [comment]
Yes.

On January 14, 2020 9:29:17 AM EST, Yuya Minami <notifications@github.com> wrote:
>Can you open other png file with `find-file` and displayed correctly?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/yuya373/emacs-slack/issues/495#issuecomment-574199879

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by yuya373** [comment]
Ok. Can you open the png file with `find-file` and displayed correctly?

**Comment by triclops200** [comment]
Unfortunately the bug seems to be a heisenbug and images are working for the past hour. I'll update this issue with that information when it happens again.

**Comment by jsilve24** [comment]
I am having this issue. 

I have cleared the cache in `slack-image-file-directory`, completely removed and rebuilt emacs-slack and dependencies but I am getting this regardless of what I do. Its been like this  since I first setup emacs-slack about 3 days ago. 

Everything else is working fine. I can see profile pictures just not these images or any other attached images. 


![slack-image-not-displaying](https://user-images.githubusercontent.com/452422/145678992-a412a479-2f5d-4b40-9279-a9ca09a122ad.png)
lack about 3 days ago.
